async function main () {
    let nftContractFactory;
    let nftContract;
    try {
        nftContractFactory = await hre.ethers.getContractFactory(
            "GearFactory_v3"
        );
        nftContract = await nftContractFactory.deploy();
        await nftContract.deployed();

        console.log("Contract deployed to:", nftContract.address);
        } catch (error) {
        console.log(error);
        process.exit(1);
    }
    const gearF = await nftContractFactory.attach(nftContract.address);
    let details = new Object();
    details.name = "Name";
    details.description = "Description";
    details.imageSVG = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="512px" height="512px" viewBox="0 0 512 512" enable-background="new 0 0 512 512" xml:space="preserve">  <image id="image0" width="512" height="512" x="0" y="0"
        href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIABAMAAAAGVsnJAAABfWlDQ1BpY2MAACiRfZE7SMNQFIb/
    pkpFKg5WEHHIUJ0s1AfiKFUsgoXSVmjVweSmL2jSkKS4OAquBQcfi1UHF2ddHVwFQfAB4ujkpOgi
    JZ6bFFrEeOByP/57/p97zwWERoWpZlcUUDXLSMVjYja3KgZeEYQPg4hiQmKmnkgvZuBZX/fUS3UX
    4VnefX9Wn5I3GeATieeYbljEG8Qzm5bOeZ84xEqSQnxOPG7QBYkfuS67/Ma56LDAM0NGJjVPHCIW
    ix0sdzArGSrxNHFYUTXKF7IuK5y3OKuVGmvdk78wmNdW0lynNYI4lpBAEiJk1FBGBRYitGukmEjR
    eczDP+z4k+SSyVUGI8cCqlAhOX7wP/g9W7MwNekmBWNA94ttf4wCgV2gWbft72Pbbp4A/mfgSmv7
    qw1g9pP0elsLHwH928DFdVuT94DLHWDoSZcMyZH8tIRCAXg/o2/KAQO3QO+aO7fWOU4fgAzNavkG
    ODgExoqUve7x7p7Ouf3b05rfD9ZPcs+D2x0GAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA
    6mAAADqYAAAXcJy6UTwAAAAYUExURQAAACIjI83S2qauuoKLmGJocejSS////z50zGIAAAABdFJO
    UwBA5thmAAAAAWJLR0QHFmGI6wAAAAlwSFlzAAAOwwAADsMBx2+oZAAAAAd0SU1FB+YMHBUVBhfN
    daMAAALaSURBVHja7drBCcMwEETRtKAW0kJaSAtpIf2XkItyEQiRYCO88+ZmMGb/O/t2K7622O77
    AAAAAAAAAAAAAAAAAAAAAADHh98nAwAAAAAAAAAA2H0nAAAAAAAAAOC88Effsw8AAAAAAAAAAAAA
    AAAAAAAAUAdgFv7qG58BAAAAAAAAAAB23w0AAAAAAAAAEA4AAAAAAAAAAAAAAAAAAAAAEA4AAAAA
    AAAAAAAAAAAAAAAAEA4AAAAAAAAAAAAAAAAAAAAkAsSGAwAAAAAAAAAAAAAAAAAAAIEAseEAAAAA
    AAAAAAAAAAAAAABAIEBsOAAAAAAAAAAAAAAAAAAAABAIEBsOAAAAAAAAAAAAAAAAAAAABALEhgMA
    AAAAAAAAAAAAAAAAAACBALHhAAAAAAAAAAAAAAAAAAAAQCBAbDgAAAAAAAAAAAAAAAAAAAAQCBAb
    DgAAAAAAAAAAAAAAAAAAAAQCxIYDAAAAAAAAAAAAAAAAAAAAgQCx4QAAAAAAAAAAAAAAAAAAAEAg
    QGw4AAAAAAAAAAAAAAAAAAAAEAgQGw4AAAAAAAAAAAAAAAAAAAAUAGjDYsIBAAAAAAAAAAAAAAAA
    AAAAAO3d1xYrEw4AAAAAAAAAAAAAAAAAAAAEA6wg7sPKhQMAAAAAAAAAAAAAAAAAAADBACuI8uEA
    AAAAAAAAAAAAAAAAAABAMMCvEOXCAQAAAAAAAAAAAAAAAAAAAABtBgEAAAAAAAAAAAAAAAAAAAAA
    qAPwDXr2rSAAAAAAAAAAAAB23w0AAAAAAAAAOD589t4Isft+AAAAAAAAAAAAAAAAAAAAAMDx4WUh
    AAAAAAAAAAAAAAAAAAAAgCCAf8Nn3wEAAAAAAAAAANjdBQAAAAAAAAA4P/yyAwAAAAAAAAAAAAAA
    AAAAAIIAvqGX/aEBAAAAAAAAAAAAAAAAAAAAAPA3QFw4AAAAAAAAAAAAAAAAAAAAkAvwAcWqRA8r
    t2HVAAAJFmVYSWZJSSoACAAAAAoAAAEEAAEAAAAAAgAAAQEEAAEAAAAAAgAAAgEDAAMAAACGAAAA
    EgEDAAEAAAABAAAAGgEFAAEAAACMAAAAGwEFAAEAAACUAAAAKAEDAAEAAAADAAAAMQECAA0AAACc
    AAAAMgECABQAAACqAAAAaYcEAAEAAAC+AAAA0AAAAAgACAAIACYAAAABAAAAJgAAAAEAAABHSU1Q
    IDIuMTAuMzIAADIwMjI6MTI6MDEgMjI6NTk6MzUAAQABoAMAAQAAAAEAAAAAAAAACQD+AAQAAQAA
    AAEAAAAAAQQAAQAAAAABAAABAQQAAQAAAAABAAACAQMAAwAAAEIBAAADAQMAAQAAAAYAAAAGAQMA
    AQAAAAYAAAAVAQMAAQAAAAMAAAABAgQAAQAAAEgBAAACAgQAAQAAAM4HAAAAAAAACAAIAAgA/9j/
    4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwg
    JC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIy
    MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAEAAQADASIAAhEB
    AxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9
    AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6
    Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ip
    qrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEB
    AQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJB
    UQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RV
    VldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6
    wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD5/ooooAKK
    KKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKK6OgAor6uoqu
    Um58o0V9XV8o0mrDOcooopDCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiig
    AooooAKKK6OgAr6uorm60SIbCucrnK9GqhHSV8o16JXndZyKRzlFFFSUFFFFABRRRQAUUUUAFFFF
    ABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRXR0AFfV1Fc3WiRDYV5zRXo1UIK85orzupbsNIK5y
    iisywooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKK6OgAr6uorm60SIb
    CvOaK9GqhBXnNFed1LdhpBXOUUVmWFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUU
    AFFFFABRRXR0AFfV1Fc3WiRDYV5zRXo1UIK85orzupbsNIK5yiisywooooAKKKKACiiigAooooAK
    KKKACiiigAooooAKKKKACiiigAooooAKKK6OgAr6uorm60SIbCvOaK9GqhBXnNFed1LdhpBXOUUV
    mWFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRXR0AFfV1Fc3WiRDYV5
    zRXo1UIK85orzupbsNIK5yiisywooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAo
    oooAKKK6OgAr6uorm60SIbCvOaK9GqhBXnNFed1LdhpBXOUUVmWFFFFABRRRQAUUUUAFFFFABRRR
    QAUUUUAFFFFABRRRQAUUUUAFFFFABRRXR0AFfV1Fc3WiRDYV5zRXo1UIK85orzupbsNIK5yiisyw
    ooooAKKKKACiiigAooooAKKKKACiiigAooooAKKK6OgDnKK6OucoAKKKKACiiujoAK+rqK5utEiG
    wrzmivRqoQV5zRXndS3YaQVzlFFZlhRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFdHX
    OUUAfZNfLNFfU1fP/wDIq/vc3ytb7+50/wAfysfLNFFfV1fQpXOU+Ua+rqK5urSJbCvOaK9GqhBX
    nNFed1LdhpBXOUUVmWFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABXR1z
    lFAH2TXyzRX1NXz/APyKv73N8rW+/udP8fysYdec153X0VX0idzjasFec0V53Q3YEgrnKKKzLCii
    igAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKK6OgAor2evGKqUbEp3
    Pqavlmivqavnf+RV/e5vla339zr/AI/lY8drzuiivoW7nIkc5RRRSKCiiigAooooAKKKKACiiigA
    ooooAKKKKACiiigAooooAKKKKACiiigAooro6ACvZ6K8YrT4SNwrnKKKzLCujrnKKAPsmvlmivqa
    vn/+RV/e5vla339zp/j+Vj42oro65yvoDmCiiigAooooAKKKKACiiigAooooAKKKKACiiigAoooo
    AKKKKACiiujoAK9norxitPhI3CucoorMsKKKKACiiigAro65yigDo65yiigAooooAKKKKACiiigA
    ooooAKKKKACiiigAooooAKKKKACiiigDo6+pq+WaK8/HYH63y+9a1+l97eZpSq8l9ArnKKK9AzCi
    iigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA//Z
    uvClKwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yOFQyMToyMTowNiswMDowMHy2Z6AAAAAl
    dEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjhUMjE6MjE6MDYrMDA6MDAN698cAAAAGnRFWHRleGlm
    OkJpdHNQZXJTYW1wbGUAOCwgOCwgOBLtPicAAAARdEVYdGV4aWY6Q29sb3JTcGFjZQAxD5sCSQAA
    ACF0RVh0ZXhpZjpEYXRlVGltZQAyMDIyOjEyOjAxIDIyOjU5OjM1My/JmgAAABN0RVh0ZXhpZjpF
    eGlmT2Zmc2V0ADE5MEyO88IAAAAUdEVYdGV4aWY6SW1hZ2VMZW5ndGgANTEyjYXRtAAAABN0RVh0
    ZXhpZjpJbWFnZVdpZHRoADUxMl75wTkAAAAadEVYdGV4aWY6U29mdHdhcmUAR0lNUCAyLjEwLjMy
    8QXWrwAAACR0RVh0ZXhpZjp0aHVtYm5haWw6Qml0c1BlclNhbXBsZQA4LCA4LCA4IBv0UwAAABx0
    RVh0ZXhpZjp0aHVtYm5haWw6Q29tcHJlc3Npb24ANvllcFcAAAAedEVYdGV4aWY6dGh1bWJuYWls
    OkltYWdlTGVuZ3RoADI1NlBwMAMAAAAddEVYdGV4aWY6dGh1bWJuYWlsOkltYWdlV2lkdGgAMjU2
    iAb6FAAAACh0RVh0ZXhpZjp0aHVtYm5haWw6SlBFR0ludGVyY2hhbmdlRm9ybWF0ADMyOJfH4cEA
    AAAvdEVYdGV4aWY6dGh1bWJuYWlsOkpQRUdJbnRlcmNoYW5nZUZvcm1hdExlbmd0aAAxOTk4mK9N
    bwAAACp0RVh0ZXhpZjp0aHVtYm5haWw6UGhvdG9tZXRyaWNJbnRlcnByZXRhdGlvbgA2EhWKGgAA
    ACB0RVh0ZXhpZjp0aHVtYm5haWw6U2FtcGxlc1BlclBpeGVsADPh181aAAAAG3RFWHRpY2M6Y29w
    eXJpZ2h0AFB1YmxpYyBEb21haW62kTFbAAAAInRFWHRpY2M6ZGVzY3JpcHRpb24AR0lNUCBidWls
    dC1pbiBzUkdCTGdBEwAAABV0RVh0aWNjOm1hbnVmYWN0dXJlcgBHSU1QTJ6QygAAAA50RVh0aWNj
    Om1vZGVsAHNSR0JbYElDAAAACXRFWHR1bmtub3duADHaIVV8AAAAAElFTkSuQmCC" />
    </svg>    
    `;
    details.level = 1;
    details.speed = 1;
    details.strenght = 1;
    details.life = 1;
    await gearF.mint(details);
    let test = await gearF.getTokenURI(1);
    console.log("result: ", test);
}

main()
.then(() => process.exit(0))
.catch(error => {
    console.error(error);
    process.exit(1);
});